### ISSUE TITLE
Dead link to Oculus Rift config page

### ISSUE THREAD

**Issue by cloudcalvin** [marcopompili/oculus-rift-direct-mode#1]
Hello! 

The link to your blog (http://blog.emarcs.org/oculus-rift-direct-mode-on-linux/) is not working.  
If you are not planning on fixing the blog post, could I ask that you post the article's contents here? 

I am trying to setup a Rift on arch linux but having trouble getting SteamVR to use direct mode. You blog seems to be the key to it all :P

Thanks a lot!

**Comment by marcopompili** [comment]
I reuploaded my Jekyll blog on GitHub, this is the link of my article: https://marcopompili.github.io/linux/xorg/oculus/2015/06/02/oculus-rift-direct-mode-on-Linux.html

It's not the key of it, but maybe you can get some guidance.

Also check this for more info: https://marcopompili.github.io/linux/xorg/oculus/2015/05/20/xorg-and-the-oculus-rift.html

Good Luck
